# Generated by Django 5.1.1 on 2024-09-11 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numStatut', models.IntegerField()),
                ('libele', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dateFabrication',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='prixHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='codeItem',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='statut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LesProduits.statut'),
            preserve_default=False,
        ),
    ]
