# Generated by Django 5.1.1 on 2024-10-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='quantité',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantité'),
        ),
    ]
